services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - ./backend:/app  
    environment:
      - PORT=4000
      - MONGO_URI=mongodb://mongo:27017/chatdb
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6
    container_name: chat-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7
    container_name: chat-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  mongo-data:
